### ISSUE TITLE
Lock rubocop version to 0.33.0

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/modulesync_config#17]
On ruby 2.1.5 and 2.1.7 I am getting the below, locking the version of rubocop in the gem file resolves this.

```
  gem 'rubocop', '0.33.0'
```

```
bundle exec rake test
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
Running RuboCop...
private method `load' called for SafeYAML:Module
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/config_loader.rb:151:in `yaml_safe_load'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/config_loader.rb:138:in `load_yaml_configuration'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/config_loader.rb:27:in `load_file'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/config_loader.rb:85:in `configuration_from_file'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/config_store.rb:40:in `for'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/target_finder.rb:112:in `excluded_dirs'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/target_finder.rb:90:in `find_files'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/target_finder.rb:31:in `find'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/runner.rb:45:in `find_target_files'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/runner.rb:29:in `run'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/cli.rb:26:in `run'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/rake_task.rb:50:in `run_cli'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/rake_task.rb:38:in `run_main_task'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/rake_task.rb:30:in `block (2 levels) in initialize'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:58:in `verbose'
/home//.rvm/gems/ruby-2.1.7/gems/rubocop-0.34.2/lib/rubocop/rake_task.rb:26:in `block in initialize'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home//.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/home//.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home//.rvm/gems/ruby-2.1.7/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home//.rvm/gems/ruby-2.1.7/bin/rake:23:in `load'
/home//.rvm/gems/ruby-2.1.7/bin/rake:23:in `<main>'
/home//.rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `eval'
/home//.rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by igalic** [comment]
aaaand that's why we only run rubocop with 2.2 for now ;)

**Comment by mkrakowitzer** [comment]
No dice

```
$ bundle exec rake rubocop 
rake aborted!
NameError: uninitialized constant Syck
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:132:in `<top (required)>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor/require_vendored.rb:4:in `require'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor.rb:40:in `require'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor.rb:40:in `require_libs'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet/vendor.rb:53:in `load_vendored'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet.rb:172:in `<module:Puppet>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-3.8.3/lib/puppet.rb:29:in `<top (required)>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/modulefile.rb:12:in `require'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/modulefile.rb:12:in `<top (required)>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith.rb:5:in `require'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith.rb:5:in `<top (required)>'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/rake_tasks.rb:3:in `require'
/home/f3792625/.rvm/gems/ruby-2.2.3/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/rake_tasks.rb:3:in `<top (required)>'
/home/f3792625/git/github/stash/Rakefile:15:in `require'
/home/f3792625/git/github/stash/Rakefile:15:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by igalic** [comment]
oh, right. puppet 3.x still has SafeYAML vendored, as @kylog explained the other day
(that's why we have it pinned to 4.x ;)
(yay! reverse engineering ~_~ )

**Comment by juniorsysadmin** [comment]
Pinned in #59 (to 0.35.0)
