### ISSUE TITLE
 No such file or directory - ./moduleroot//spec/spec_helper_acceptance.rb

### ISSUE THREAD

**Issue by dhoppe** [voxpupuli/modulesync_config#44]
Why is this file missing and how do I get rid of this error message?

```
Syncing puppet-kafka
Overriding any local changes to repositories in ./modules
Switching to branch modulesync
/Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/lib/modulesync/renderer.rb:14:in `read': No such file or directory - ./moduleroot//spec/spec_helper_acceptance.rb (Errno::ENOENT)
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/lib/modulesync/renderer.rb:14:in `build'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/lib/modulesync.rb:77:in `block (2 levels) in run'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/lib/modulesync.rb:68:in `each'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/lib/modulesync.rb:68:in `block in run'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/lib/modulesync.rb:57:in `each'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/lib/modulesync.rb:57:in `run'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/gems/modulesync-0.6.1/bin/msync:8:in `<top (required)>'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/bin/msync:23:in `load'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/bin/msync:23:in `<main>'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dhoppe/.rvm/gems/ruby-2.0.0-p643@puppet-community/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by igalic** [comment]
to answer the only question i have here:
[puppet-kafka's .sync.yml](https://github.com/puppet-community/puppet-kafka/blob/master/.sync.yml)
```yaml
---
spec/spec_helper_acceptance.rb:
  dependencies:
    - puppetlabs-stdlib
    - puppetlabs-java
spec/acceptance/nodesets/windows-2008R2-serverstandard-x64.yml:
  unmanaged: true
```

**Comment by danzilio** [comment]
Yeah, `.sync.yml` is trying to manage a file that doesn't exist in the moduleroot. We should have better error messages.

**Comment by dhoppe** [comment]
This issue has been solved, by fixing the ```.sync.yml```.
