### ISSUE TITLE
Error updating module

### ISSUE THREAD

**Issue by xaque208** [voxpupuli/modulesync_config#449]
Hi.  After being away for a while and attempting to use the newest modulesync code, I get the following error when trying to update a few of my modules.  I suspect there may be something wrong with the module itself, in that it might not conform in some way, but what is the issue?

```
Error while updating puppet-ldapquery
/home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/settings.rb:25:in `merge': no implicit conversion of String into Hash (TypeError)
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/settings.rb:25:in `build_file_configs'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/settings.rb:30:in `block in managed?'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/2.4.0/pathname.rb:327:in `ascend'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/settings.rb:29:in `managed?'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/settings.rb:46:in `block in unmanaged_files'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/settings.rb:45:in `select'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/settings.rb:45:in `unmanaged_files'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync.rb:107:in `manage_module'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync.rb:135:in `block in update'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync.rb:133:in `each'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync.rb:133:in `update'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/lib/modulesync/cli.rb:120:in `update'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /home/zach/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/modulesync-0.8.2/bin/msync:8:in `<top (required)>'
	from /home/zach/.rbenv/versions/2.4.3/bin/msync:23:in `load'
	from /home/zach/.rbenv/versions/2.4.3/bin/msync:23:in `<main>'
```

**Comment by ekohl** [comment]
Could you retry with the latest modulesync and see if it persists?

**Comment by xaque208** [comment]
I'm not receiving this error any longer.
